Updated videolinks to be embedded links
Epiko1994/MeFitBackend pull request #22
Opened 2022-03-15 14:31 UTC by livstella

2022-03-15 14:53 UTC, AllanTC requested changes
set_id mangler

2022-03-15 15:00 UTC, AllanTC requested changes
Mangler commaer :)

2022-03-15 15:02 UTC, AllanTC approved these changes

2022-03-16 09:23 UTC, Epiko1994 approved these changes

2022-03-16 11:23 UTC, merged